### ISSUE TITLE
[feature]: 统一错误类型

### ISSUE THREAD

**Issue by fansehep** [shaun-io/shaun-rs#10]
当前 parser.rs 使用 Result<Statement, String>, 使用 String 来返回一个错误, 这实在是不太优雅. 应该要统一错误类型 😢

**Comment by Tangruilin** [comment]
@fansehep 错误类型我们需要设计一下，我看现在的错误类型还不是很完整

这个事情优先级【中高】，以免后面代码多了修改错误类型比较麻烦

**Comment by fansehep** [comment]
> @fansehep 错误类型我们需要设计一下，我看现在的错误类型还不是很完整
> 
> 这个事情优先级【中高】，以免后面代码多了修改错误类型比较麻烦

这里还是比较紧急的, 尽早统一吧,  避免后续太多代码重构. 👍🏻

**Comment by fansehep** [comment]
包装 Result, 需要看看 有什么办法在 Err 的时候包装一层, 附带上 `std::line!(), std::file!()` 携带上发生错误的文件名称和行号, 方便定位.
