### ISSUE TITLE
[doc]: choose a LICENSE to our project.

### ISSUE THREAD

**Issue by fansehep** [shaun-io/shaun-rs#21]
cc @Tangruilin 我们需要选择一个 LICENSE 来许可我们的项目. 我想选择 Apache LICENSE 2.0, 如何?

**Comment by Tangruilin** [comment]
> cc @Tangruilin 我们需要选择一个 LICENSE 来许可我们的项目. 我想选择 Apache LICENSE 2.0, 如何?

我现在增加 LICENSE
